services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_MODE: "PROD"
        REACT_APP_API_URL: "http://34.88.151.132/api"
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"


  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    command: /bin/sh -c "while [ ! -f /usr/share/nginx/html/index.html ]; do echo 'Waiting for frontend build...'; sleep 5; done && nginx -g 'daemon off;'"

networks:
  app-network:
    driver: bridge

volumes:
  db_data: