import { AppDataSource } from '../ormconfig';
import { Vaccine } from '../entities/Vaccine';

export const seedVaccines = async () => {

    const vaccineRepository = AppDataSource.getRepository(Vaccine);

    const vaccines = [
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Rotavirus',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'M',
            vaccine_minimum_recommend_date: 2,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 1,
            vaccine_description: 'Rotavirus vaccine',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Pneumokokkitaudit (PCV)',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'M',
            vaccine_minimum_recommend_date: 3,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 1,
            vaccine_description: 'Aivokalvontulehdus, keuhkokuume, verenmyrkytys ja korvatulehdus',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Viitosrokote (DTP-IPV-Hib)',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'M',
            vaccine_minimum_recommend_date: 3,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 1,
            vaccine_description: 'Kurkkumätä, jäykkäkouristus, hinkuyskä, polio ja Hib-taudit, kuten aivokalvontulehdus, kurkunkannen tulehdus ja verenmyrkytys',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Rotavirus',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'M',
            vaccine_minimum_recommend_date: 3,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 2,
            vaccine_description: 'Seasonal influenza vaccine',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Pneumokokkitaudit (PCV)',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'M',
            vaccine_minimum_recommend_date: 5,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 2,
            vaccine_description: 'Aivokalvontulehdus, keuhkokuume, verenmyrkytys ja korvatulehdus',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Viitosrokote (DTP-IPV-Hib)',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'M',
            vaccine_minimum_recommend_date: 5,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 2,
            vaccine_description: 'Kurkkumätä, jäykkäkouristus, hinkuyskä, polio ja Hib-taudit, kuten aivokalvontulehdus, kurkunkannen tulehdus ja verenmyrkytys',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Rotavirus',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'M',
            vaccine_minimum_recommend_date: 5,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 3,
            vaccine_description: 'Rotavirus vaccine',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Kausi-influenssa',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'M',
            vaccine_minimum_recommend_date: 6,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 1,
            vaccine_description: 'vuosittain',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Pneumokokkitaudit (PCV)',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'M',
            vaccine_minimum_recommend_date: 12,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 3,
            vaccine_description: 'Aivokalvontulehdus, keuhkokuume, verenmyrkytys ja korvatulehdus',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Viitosrokote (DTP-IPV-Hib)',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'M',
            vaccine_minimum_recommend_date: 12,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 3,
            vaccine_description: 'Kurkkumätä, jäykkäkouristus, hinkuyskä, polio ja Hib-taudit, kuten aivokalvontulehdus, kurkunkannen tulehdus ja verenmyrkytys',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Tuhkarokko, sikotauti, vihurirokko (MPR)',
            vaccine_is_periodical: true,
            vaccine_minimum_period_type: 'M',
            vaccine_minimum_recommend_date: 12,
            vaccine_maximum_period_type: 'M',
            vaccine_maximum_recommend_date: 18,
            vaccine_round: 1,
            vaccine_description: 'Kurkkumätä, jäykkäkouristus, hinkuyskä, polio ja Hib-taudit, kuten aivokalvontulehdus, kurkunkannen tulehdus ja verenmyrkytys',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Kausi-influenssa',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'Y',
            vaccine_minimum_recommend_date: 1,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 2,
            vaccine_description: 'vuosittain',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Vesirokko',
            vaccine_is_periodical: true,
            vaccine_minimum_period_type: 'M',
            vaccine_minimum_recommend_date: 18,
            vaccine_maximum_period_type: 'Y',
            vaccine_maximum_recommend_date: 11,
            vaccine_round: 2,
            vaccine_description: 'Vesirokko vaccine',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Kausi-influenssa',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'Y',
            vaccine_minimum_recommend_date: 2,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 3,
            vaccine_description: 'vuosittain',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Kausi-influenssa',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'Y',
            vaccine_minimum_recommend_date: 3,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 4,
            vaccine_description: 'vuosittain',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Kausi-influenssa',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'Y',
            vaccine_minimum_recommend_date: 4,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 5,
            vaccine_description: 'vuosittain',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Nelosrokote (DTaP-IPV)',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'Y',
            vaccine_minimum_recommend_date: 4,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 1,
            vaccine_description: 'Kurkkumätä, jäykkäkouristus, hinkuyskä, polio',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Kausi-influenssa',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'Y',
            vaccine_minimum_recommend_date: 5,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 6,
            vaccine_description: 'vuosittain',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Kausi-influenssa',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'Y',
            vaccine_minimum_recommend_date: 6,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 7,
            vaccine_description: 'vuosittain',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Tuhkarokko, sikotauti, vihurirokko, vesirokko (MPRV)',
            vaccine_is_periodical: false,
            vaccine_minimum_period_type: 'Y',
            vaccine_minimum_recommend_date: 6,
            vaccine_maximum_period_type: null,
            vaccine_maximum_recommend_date: null,
            vaccine_round: 1,
            vaccine_description: 'MPRV vaccine',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'HPV-infektiot',
            vaccine_is_periodical: true,
            vaccine_minimum_period_type: 'Y',
            vaccine_minimum_recommend_date: 10,
            vaccine_maximum_period_type: 'Y',
            vaccine_maximum_recommend_date: 12,
            vaccine_round: 1,
            vaccine_description: 'HPV-infektiot vaccine',
        },
        {
            vaccine_national_code: 'FIN',
            vaccine_name: 'Kurkkumätä, jäykkäkouristus, hinkuyskä (dtap-tehoste)',
            vaccine_is_periodical: true,
            vaccine_minimum_period_type: 'Y',
            vaccine_minimum_recommend_date: 14,
            vaccine_maximum_period_type: 'Y',
            vaccine_maximum_recommend_date: 15,
            vaccine_round: 1,
            vaccine_description: 'dtap-tehoste vaccine',
        },

    ];

    for (const vaccine of vaccines) {
        const existingVaccine = await vaccineRepository.findOne({
            where: {
                vaccine_name: vaccine.vaccine_name,
                vaccine_round: vaccine.vaccine_round,
            },
        });
        if (!existingVaccine) {
            await vaccineRepository.save(vaccine);
        }
    }

    console.log('Vaccine data seeded successfully');
};
