name: deploy.yml
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16'

      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false

      - name: Clean up node_modules after test
        working-directory: ./frontend
        run: rm -rf node_modules

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Transfer code to GCP
        run: |
          scp -o StrictHostKeyChecking=no -r * ${{ secrets.GCP_USER }}@${{ secrets.GCP_IP }}:/var/www/fullstack

      - name: Deploy on GCP
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USER }}@${{ secrets.GCP_IP }} "cd /var/www/fullstack && docker compose down && docker compose up -d --build" && docker image prune -f
